/**
 * Generated by scripts/generate-api-reference.js — do not edit.
 *
 * The field tables come from the interfaces in src/models/PublicContent.ts and
 * the endpoint list from src/routes/api/v1.ts. Change those and re-run the
 * generator; a test fails when this file stops matching them.
 */

export const ENDPOINTS = [
  {
    method: 'GET',
    path: '/api/v1/posts',
    scope: 'content:read',
    shape: 'PublicPost',
    collection: true,
    summary: 'Published posts, newest first.'
  },
  {
    method: 'GET',
    path: '/api/v1/posts/:slug',
    scope: 'content:read',
    shape: 'PublicPost',
    collection: false,
    summary: 'One published post, by slug or id.'
  },
  {
    method: 'GET',
    path: '/api/v1/pages',
    scope: 'content:read',
    shape: 'PublicPage',
    collection: true,
    summary: 'Published pages, newest first.'
  },
  {
    method: 'GET',
    path: '/api/v1/pages/:slug',
    scope: 'content:read',
    shape: 'PublicPage',
    collection: false,
    summary: 'One published page, by slug or id.'
  },
  {
    method: 'GET',
    path: '/api/v1/authors',
    scope: 'content:read',
    shape: 'PublicAuthor',
    collection: false,
    summary: 'Every author with something published.'
  },
  {
    method: 'GET',
    path: '/api/v1/authors/:slug',
    scope: 'content:read',
    shape: 'PublicAuthor',
    collection: false,
    summary: 'One author, by slug or id.'
  },
  {
    method: 'GET',
    path: '/api/v1/categories',
    scope: 'content:read',
    shape: 'PublicCategory',
    collection: false,
    summary: 'Every category, with post counts.'
  },
  {
    method: 'GET',
    path: '/api/v1/tags',
    scope: 'content:read',
    shape: 'PublicTag',
    collection: false,
    summary: 'Every tag, with post counts.'
  },
  {
    method: 'GET',
    path: '/api/v1/media/:id',
    scope: 'media:read',
    shape: 'PublicMedia',
    collection: false,
    summary: 'One media item, by id.'
  }
]

export const QUERY_PARAMS = [
  { name: 'author', description: 'Filter posts by author slug or id — an author archive.' },
  { name: 'category', description: 'Filter posts by category slug or id.' },
  { name: 'format', description: '`markdown` returns the source. Anything else returns rendered HTML.' },
  { name: 'page', description: 'Which page of results. Defaults to 1.' },
  { name: 'per_page', description: 'Results per page. Defaults to 10, clamped to 100.' },
  { name: 'search', description: 'Filter posts whose title or excerpt contains this text.' },
  { name: 'tag', description: 'Filter posts by tag slug or id.' }
]

export const SHAPES = [
  {
    name: 'PublicPost',
    description: 'A post as the content API returns it.',
    fields: [
      { name: 'id', type: 'number', description: 'Stable identifier. Accepted anywhere a slug is.' },
      { name: 'slug', type: 'string | null', description: 'URL segment. Null on posts written before slugs existed.' },
      { name: 'title', type: 'string', description: 'Plain text, never markup.' },
      { name: 'excerpt', type: 'string | null', description: 'Short summary, if the author wrote one.' },
      { name: 'content', type: 'string', description: 'The body, in whichever `format` this item reports.' },
      { name: 'format', type: '\'html\' | \'markdown\'', description: 'What `content` actually is — not what you asked for. See `?format=`.' },
      { name: 'featured_image_url', type: 'string | null', description: 'Absolute URL of the featured image, or null.' },
      { name: 'author', type: 'string | null', description: 'The author\'s display name. Never their address.' },
      { name: 'author_profile', type: '{ id: number; name: string; slug: string | null; bio: string | null; website: string | null; avatar_url: string | null } | null', description: 'The author\'s profile — biography, link and avatar. Null if the account is gone.' },
      { name: 'categories', type: 'Array<{ id: number; name: string; slug: string }>', description: 'Every category on the post. Empty when uncategorised.' },
      { name: 'tags', type: 'Array<{ id: number; name: string; slug: string }>', description: 'Every tag on the post. Empty when untagged.' },
      { name: 'meta_title', type: 'string | null', description: 'SEO title override, if set.' },
      { name: 'meta_description', type: 'string | null', description: 'SEO description override, if set.' },
      { name: 'published_at', type: 'string', description: 'When it was created, ISO 8601. Posts are ordered by this, newest first.' },
      { name: 'updated_at', type: 'string', description: 'When it last changed, ISO 8601.' }
    ]
  },
  {
    name: 'PublicPage',
    description: 'A page as the content API returns it. A post without the blog machinery.',
    fields: [
      { name: 'id', type: 'number', description: 'Stable identifier. Accepted anywhere a slug is.' },
      { name: 'slug', type: 'string', description: 'URL segment. Required on pages, unlike posts.' },
      { name: 'title', type: 'string', description: 'Plain text, never markup.' },
      { name: 'content', type: 'string', description: 'The body, in whichever `format` this item reports.' },
      { name: 'format', type: '\'html\' | \'markdown\'', description: 'What `content` actually is — not what you asked for. See `?format=`.' },
      { name: 'featured_image_url', type: 'string | null', description: 'Absolute URL of the featured image, or null.' },
      { name: 'meta_title', type: 'string | null', description: 'SEO title override, if set.' },
      { name: 'meta_description', type: 'string | null', description: 'SEO description override, if set.' },
      { name: 'published_at', type: 'string', description: 'When it was created, ISO 8601.' },
      { name: 'updated_at', type: 'string', description: 'When it last changed, ISO 8601.' }
    ]
  },
  {
    name: 'PublicAuthor',
    description: 'An author, as a byline and an archive page need them.',
    fields: [
      { name: 'id', type: 'number', description: 'Stable identifier. Accepted anywhere a slug is.' },
      { name: 'name', type: 'string', description: 'Display name, as it appears on a byline.' },
      { name: 'slug', type: 'string | null', description: 'URL segment for the author\'s archive. Accepted by `?author=`.' },
      { name: 'bio', type: 'string | null', description: 'The biography they wrote, if any.' },
      { name: 'website', type: 'string | null', description: 'Their own site, if they gave one.' },
      { name: 'avatar_url', type: 'string | null', description: 'Absolute URL of their avatar, or null.' },
      { name: 'post_count', type: 'number', description: 'How many published posts they have. Never zero — unpublished authors are not listed.' }
    ]
  },
  {
    name: 'PublicCategory',
    description: 'A category, with how many published posts sit in it.',
    fields: [
      { name: 'id', type: 'number', description: 'Stable identifier.' },
      { name: 'name', type: 'string', description: 'Display name.' },
      { name: 'slug', type: 'string', description: 'URL segment. Accepted by `?category=`.' },
      { name: 'description', type: 'string | null', description: 'Longer description, if one was written.' },
      { name: 'post_count', type: 'number', description: 'Published posts in this category. Zero is returned, not omitted.' }
    ]
  },
  {
    name: 'PublicTag',
    description: 'A tag, with how many published posts carry it.',
    fields: [
      { name: 'id', type: 'number', description: 'Stable identifier.' },
      { name: 'name', type: 'string', description: 'Display name.' },
      { name: 'slug', type: 'string', description: 'URL segment. Accepted by `?tag=`.' },
      { name: 'post_count', type: 'number', description: 'Published posts carrying this tag.' }
    ]
  },
  {
    name: 'PublicMedia',
    description: 'A media item.',
    fields: [
      { name: 'id', type: 'number', description: 'Stable identifier.' },
      { name: 'url', type: 'string', description: 'Absolute URL of the file.' },
      { name: 'mime_type', type: 'string', description: 'MIME type as recorded at upload.' },
      { name: 'size', type: 'number', description: 'Size in bytes.' },
      { name: 'alt_text', type: 'string | null', description: 'Alt text, if an editor supplied one.' },
      { name: 'created_at', type: 'string', description: 'When it was uploaded, ISO 8601.' }
    ]
  }
]

export const ENVELOPE = {
  item: '{ "data": <object> }',
  collection: '{ "data": [<object>], "meta": { "page", "per_page", "total", "total_pages" } }',
  error: '{ "error": "Not found" }'
}
